# Generated by Django 4.1.7 on 2023-10-17 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_transaction_dst_alter_transaction_src'),
    ]

    operations = [
        migrations.RunSQL("update budget_transaction set src_id=null where src_id in (select id from budget_compte where nom='Externe')"),
        migrations.RunSQL("update budget_transaction set dst_id=null where dst_id in (select id from budget_compte where nom='Externe')")
    ]
