
services:

  mybudget:
    image: org.menie/mybudget:3.3
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: mybudget
    restart: unless-stopped
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - ../data:/data
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
